import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Header from "@/components/global/Header";
import { getCachedArticleCategories, getCachedQuickLinks } from "@/services/CachedServices";
import QuickLinks from "@/components/global/QuickLinks";
import Footer from "@/components/global/Footer";

const InterFont = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-inter",
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// **1. Define the Organization Schema JSON-LD separately for clarity**
const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Jagran Reviews",
  "url": "https://www.jagranreviews.com/",
  "logo": {
    "@type": "ImageObject",
    "url": process.env.NEXT_PUBLIC_BASE_SITE_SCHEMA_LOGO,
    "width": 600,
    "height": 60
  },
  "sameAs": [
    "https://www.facebook.com/jagranreviews",
    "https://www.instagram.com/jagranreviews",
    "https://x.com/jagranreviews",
    "https://www.youtube.com/@jagranreviews"
  ],
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "20th Floor, World Trade Tower",
    "addressLocality": "Noida Sector 16",
    "addressRegion": "Uttar Pradesh",
    "postalCode": "201301",
    "addressCountry": {
      "@type": "Country",
      "name": "IN"
    }
  },
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+91-120-4694000",
    "contactType": "Customer Service",
    "areaServed": "IN",
    "availableLanguage": "English",
    "hoursAvailable": {
      "@type": "OpeningHoursSpecification",
      "opens": "09:00",
      "closes": "18:00"
    }
  }
};

const comscoreAarray=[];
comscoreAarray.push(`
    var _comscore = _comscore || [];_comscore.push({ c1: "2", c2: "13184768", cs_ucfr: "1" }); (function() {var s = document.createElement("script"), el = document.getElementsByTagName("script")[0];s.async = true;s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b")+ ".scorecardresearch.com/beacon.js"; el.parentNode.insertBefore(s, el); })();
`);

export default async function RootLayout({ children }) {
  const articleCategoriesPromise = getCachedArticleCategories();
  const quickLinksPromise = getCachedQuickLinks();
  const [ articleCategoriesResult, quickLinksResult ] = await Promise.allSettled([ articleCategoriesPromise, quickLinksPromise ]);
  const articleCategoriesData = articleCategoriesResult.status === 'fulfilled' ? articleCategoriesResult.value : null;  
  const quickLinksData = quickLinksResult.status === 'fulfilled' ? quickLinksResult.value : null;  
  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href="https://img.jagranreviews.com/" />
        <link rel="preconnect" href="https://img.jagranreviews.com/" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://www.google-analytics.com" />
        <link rel="preconnect" href="https://sb.scorecardresearch.com" />
      </head>
      <body className={`${InterFont.variable} antialiased`}>
        <Script id="jsonld-organization" type="application/ld+json" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W5NRHHKF" height="0" width="0" style={{display:"none",visibility:"hidden"}}></iframe>
        <Script id='gtm'>{`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-W5NRHHKF');`}</Script>
        <Header header={articleCategoriesData} />
        {children}
        <QuickLinks QuickLinkData={quickLinksData} />
        <Footer />
        <script type="text/javascript" async={true} dangerouslySetInnerHTML={{__html: comscoreAarray }} ></script>
      </body>
    </html>
  );
}
