import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Header from "@/components/global/Header";
import { getCachedArticleCategories, getCachedQuickLinks } from "@/services/CachedServices";
import QuickLinks from "@/components/global/QuickLinks";
import Footer from "@/components/global/Footer";

// Load font variable only once and remove unneeded comment
const inter = Inter({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400",
    "500", "600", "700", "800", "900"
  ],
  display: "swap",
  variable: "--font-inter",
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ORGANIZATION_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Jagran Reviews",
  url: "https://www.jagranreviews.com/",
  logo: {
    "@type": "ImageObject",
    url: process.env.NEXT_PUBLIC_BASE_SITE_SCHEMA_LOGO,
    width: 600,
    height: 60,
  },
  sameAs: [
    "https://www.facebook.com/jagranreviews",
    "https://www.instagram.com/jagranreviews",
    "https://x.com/jagranreviews",
    "https://www.youtube.com/@jagranreviews",
  ],
  address: {
    "@type": "PostalAddress",
    streetAddress: "20th Floor, World Trade Tower",
    addressLocality: "Noida Sector 16",
    addressRegion: "Uttar Pradesh",
    postalCode: "201301",
    addressCountry: {
      "@type": "Country",
      name: "IN",
    },
  },
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+91-120-4694000",
    contactType: "Customer Service",
    areaServed: "IN",
    availableLanguage: "English",
    hoursAvailable: {
      "@type": "OpeningHoursSpecification",
      opens: "09:00",
      closes: "18:00",
    },
  },
};

// Updated COMSCORE_INLINE_SCRIPT with useCache (cache lifetime hint for browser)
// See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-usecache
const COMSCORE_INLINE_SCRIPT = `
var _comscore=_comscore||[];
_comscore.push({c1:"2",c2:"13184768",cs_ucfr:"1"});
(function(){
  var s=document.createElement("script"),
      el=document.getElementsByTagName("script")[0];
  s.async=true;
  s.src=(document.location.protocol=="https:"?"https://sb":"http://b")+".scorecardresearch.com/beacon.js";
  // Use 'fetchPriority' and 'setAttribute("cache-control", ...)' if browser supports, else default
  // Try to use 'useCache' attribute for a long cache lifetime if supported
  s.setAttribute && s.setAttribute("useCache", "true"); // hint for caching if browser honors
  el.parentNode.insertBefore(s,el);
})();
`;

export default async function RootLayout({ children }) {
  // Fetch initial data in parallel, only await after all have been triggered
  const [articleCategoriesResult, quickLinksResult] = await Promise.allSettled([
    getCachedArticleCategories(),
    getCachedQuickLinks(),
  ]);
  const articleCategoriesData = articleCategoriesResult.status === "fulfilled"
    ? articleCategoriesResult.value
    : undefined;
  const quickLinksData = quickLinksResult.status === "fulfilled"
    ? quickLinksResult.value
    : undefined;

  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href="https://img.jagranreviews.com/" />
        <link rel="preconnect" href="https://img.jagranreviews.com/" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://www.google-analytics.com" />
        <link rel="preconnect" href="https://sb.scorecardresearch.com" />
      </head>
      <body className={`${inter.variable} antialiased`}>
        <Script
          id="jsonld-organization"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(ORGANIZATION_SCHEMA) }}
        />
        {/* Place GTM iframe as early as possible, hide visually for performance/tracking */}
        <iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-W5NRHHKF"
          height="0"
          width="0"
          title="GTM"
          style={{ display: "none", visibility: "hidden" }}
        />
        {/* GTM Bootstrap Script */}
        <Script id="gtm" strategy="afterInteractive">{`
          (function(w,d,s,l,i){
            w[l]=w[l]||[];
            w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
            var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
            j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
            f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-W5NRHHKF');
        `}</Script>
        <Header header={articleCategoriesData} />
        {children}
        <QuickLinks QuickLinkData={quickLinksData} />
        <Footer />
        {/* Comscore beacon: load lazily for performance, with cache usage hint */}
        <Script
          id="comscore-beacon"
          type="text/javascript"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{ __html: COMSCORE_INLINE_SCRIPT }}
        />
      </body>
    </html>
  );
}
